# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryDescription',
            fields=[
                ('category_id', models.AutoField(db_column='CATEGORY_ID', primary_key=True, serialize=False)),
                ('category_name', models.CharField(blank=True, db_column='CATEGORY_NAME', max_length=255, null=True, unique=True)),
                ('description', models.CharField(blank=True, db_column='DESCRIPTION', max_length=255, null=True)),
            ],
            options={
                'db_table': 'CATEGORY_DESCRIPTION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, db_column='MESSAGE', max_length=1000, null=True)),
            ],
            options={
                'db_table': 'FEEDBACK',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LogData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, db_column='TIMESTAMP', null=True)),
                ('url', models.CharField(blank=True, db_column='URL', max_length=1000, null=True)),
                ('parameters', models.CharField(blank=True, db_column='PARAMETERS', max_length=1000, null=True)),
                ('responsecode', models.IntegerField(blank=True, db_column='RESPONSECODE', null=True)),
                ('ipaddress', models.CharField(blank=True, db_column='IPADDRESS', max_length=1000, null=True)),
                ('executiontime', models.IntegerField(blank=True, db_column='EXECUTIONTIME', null=True)),
                ('requesttype', models.CharField(blank=True, db_column='REQUESTTYPE', max_length=255, null=True)),
            ],
            options={
                'db_table': 'LOG_DATA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('order_detail_id', models.AutoField(db_column='ORDER_DETAILS_ID', primary_key=True, serialize=False)),
                ('quantity_ordered', models.IntegerField(blank=True, db_column='QUANTITY_ORDERED', null=True)),
                ('cost_price', models.FloatField(blank=True, db_column='COST_PRICE', null=True)),
                ('selling_price', models.FloatField(blank=True, db_column='SELLING_PRICE', null=True)),
            ],
            options={
                'db_table': 'ORDER_DETAILS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(db_column='ORDER_ID', primary_key=True, serialize=False)),
                ('order_date', models.DateField(blank=True, db_column='ORDER_DATE', null=True)),
                ('status', models.CharField(blank=True, db_column='STATUS', max_length=100, null=True)),
                ('deleted', models.TextField(blank=True, db_column='DELETED', null=True)),
            ],
            options={
                'db_table': 'ORDERS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(db_column='PRODUCT_ID', primary_key=True, serialize=False)),
                ('product_description', models.CharField(blank=True, db_column='PRODUCT_DESCRIPTION', max_length=1000, null=True)),
                ('cost_price', models.FloatField(blank=True, db_column='COST_PRICE', null=True)),
                ('selling_price', models.FloatField(blank=True, db_column='SELLING_PRICE', null=True)),
                ('quantity_in_stock', models.IntegerField(blank=True, db_column='QUANTITY_IN_STOCK', null=True)),
                ('product_code', models.CharField(blank=True, db_column='PRODUCT_CODE', max_length=100, null=True)),
                ('product_name', models.CharField(blank=True, db_column='PRODUCT_NAME', max_length=100, null=True)),
                ('is_available', models.TextField(blank=True, db_column='IS_AVAILABLE', null=True)),
            ],
            options={
                'db_table': 'PRODUCT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('user_id', models.AutoField(db_column='USER_ID', primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, db_column='COMPANY_NAME', max_length=100, null=True, unique=True)),
                ('contact_first_name', models.CharField(blank=True, db_column='CONTACT_FIRST_NAME', max_length=100, null=True)),
                ('phone', models.CharField(blank=True, db_column='PHONE', max_length=100, null=True)),
                ('contact_last_name', models.CharField(blank=True, db_column='CONTACT_LAST_NAME', max_length=100, null=True)),
                ('address_line', models.CharField(blank=True, db_column='ADDRESS_LINE', max_length=100, null=True)),
                ('city', models.CharField(blank=True, db_column='CITY', max_length=100, null=True)),
                ('state', models.CharField(blank=True, db_column='STATE', max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, db_column='POSTAL_CODE', max_length=100, null=True)),
                ('country', models.CharField(blank=True, db_column='COUNTRY', max_length=100, null=True)),
            ],
            options={
                'db_table': 'USER_DETAILS',
                'managed': False,
            },
        ),
    ]
